-- Your SQL goes here
ALTER TABLE users
ADD COLUMN pass VARCHAR NOT NULL,
ADD COLUMN phone VARCHAR NOT NULL,
ADD COLUMN email VARCHAR NOT NULL,
ADD COLUMN username VARCHAR NOT NULL,
ADD COLUMN lastname VARCHAR NOT NULL;